name: A Workflow for Hello World File
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Ilham"  
